# Generated by Django 5.1.5 on 2025-01-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='newsletter_abo',
            field=models.BooleanField(default=True),
        ),
    ]
