# Generated by Django 5.1.5 on 2025-01-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superstore', '0002_customer_newsletter_abo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_address',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
