# Generated by Django 5.1.5 on 2025-01-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superstore', '0004_bill_product_order_producttype_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['last_name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
