# Generated by Django 5.1.5 on 2025-01-30 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superstore', '0005_alter_customer_options_customer_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='slug',
        ),
    ]
